apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    # Configured to dynamically load the URL from your environment variables
    url: ${INFLUXDB_URL}
    jsonData:
      version: Flux
      organization: greenlink
      defaultBucket: sensor_data
      tlsSkipVerify: true
    secureJsonData:
      token: your_influxdb_token_here
    isDefault: true
    editable: true
