apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://localhost:8086
    jsonData:
      version: Flux
      organization: greenlink
      defaultBucket: sensor_data
      tlsSkipVerify: true
    secureJsonData:
      token: your_influxdb_token_here
    isDefault: true
    editable: true
